"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
[$os](white)\
[ ](bg:white)\
[](fg:white bg:purple)\
$directory\
${custom.notgit}\
$git_branch\
$git_state\
$git_metrics\
$git_status\
$cmd_duration\
$time\
[](fg:comment)\
$line_break\
$character\
"""

palette = 'dracula'

[os]
disabled = false
style = "bg:white fg:crust"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:purple fg:crust"
style_root = "bg:purple fg:crust"
format = '[ $user]($style)'

[directory]
style = "bg:purple fg:crust"
format = "[   $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[custom.notgit]
when = "! git rev-parse --is-inside-work-tree >/dev/null 2>&1"
command = "echo not git"
format = '[](fg:purple bg:comment)'

[git_branch]
symbol = ""
style = "bg:green fg:crust"
format = '[](fg:purple bg:green)[ $symbol $branch ]($style)'

[git_state]
style = "bg:green fg:comment"
format = '[ \($state( $progress_current/$progress_total)\) ]($style)'

[git_status]
style = "bg:green fg:crust"
format = '[($all_status$ahead_behind )]($style)[](fg:green bg:comment)'

[git_metrics]
disabled = false
added_style="fg:comment bg:green"
deleted_style="fg:red bg:green"
format = '[+$added ]($added_style)[-$deleted ]($deleted_style)'

[nodejs]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[c]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[rust]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[haskell]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[python]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:crust bg:green)]($style)'

[docker_context]
symbol = ""
style = "bg:comment"
format = '[[ $symbol( $context) ](fg:crust bg:comment)]($style)'


[time]
disabled = false
time_format = "%H:%M:%S"
style = "bg:comment fg:crust"
format = '[   $time ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:purple)'
vimcmd_replace_symbol = '[❮](bold fg:purple)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[cmd_duration]
show_milliseconds = true
format = "[  in $duration ](bg:purple fg:crust)"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[palettes.dracula]

pink = "#ff79c6"
red = "#ff5555"
yellow = "#f1fa8c"
green = "#50fa7b"
blue = "#644ac9"
purple = "#bd93f9"
cyan = "#8be9fd"
comment = "#6272a4"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
