"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
[$os](white)\
[ ](bg:white)\
[](fg:white bg:purple)\
$directory\
[](fg:purple bg:green)\
$git_branch\
$git_status\
[](fg:green)\
$cmd_duration\
$line_break\
$character"""

right_format = """
[](green)\
$c\
$rust\
$haskell\
$python\
[](fg:green bg:comment)\
$time\
[ ](fg:comment)"""

palette = 'dracula'

[os]
disabled = false
style = "bg:white fg:crust"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:purple fg:crust"
style_root = "bg:purple fg:crust"
format = '[ $user]($style)'

[directory]
style = "bg:purple fg:crust"
format = "[   $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:green"
format = '[[ $symbol $branch ](fg:crust bg:green)]($style)'

[git_status]
style = "bg:green"
format = '[[($all_status$ahead_behind )](fg:crust bg:green)]($style)'

[nodejs]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[c]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[rust]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[haskell]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[python]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:crust bg:green)]($style)'

[docker_context]
symbol = ""
style = "bg:comment"
format = '[[ $symbol( $context) ](fg:crust bg:comment)]($style)'


[time]
disabled = false
time_format = "%H:%M:%S"
style = "bg:comment"
format = '[[   $time ](fg:crust bg:comment)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:purple)'
vimcmd_replace_symbol = '[❮](bold fg:purple)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[cmd_duration]
show_milliseconds = true
format = "  in $duration "
style = "bg:purple"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[palettes.dracula]

pink = "#ff79c6"
red = "#ff5555"
yellow = "#f1fa8c"
green = "#50fa7b"
blue = "#644ac9"
purple = "#bd93f9"
cyan = "#8be9fd"
comment = "#6272a4"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
