wallpaper {
  monitor = DP-2
  path = ~/Pictures/Backgrounds/iss_sts129_big.jpg
  fit_mode = cover
}

wallpaper {
  monitor=HDMI-A-2
  path = ~/Pictures/Backgrounds/sts30nightlaunch_nasa_big.jpg
  fit_mode = cover
}


# mwcenter_gendler_big.jpg
