wallpaper {
  monitor = DP-1
  path = ~/Pictures/Backgrounds/
  fit_mode = cover
}

wallpaper {
  monitor=HDMI-A-2
  path = ~/Pictures/Backgrounds/
  fit_mode = cover
}

splash = false
# mwcenter_gendler_big.jpg
